# Generated by Django 3.1.3 on 2020-11-28 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20201128_0353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_update', 'Can update'), ('can_delete', 'Can delete'), ('can_create', 'Can create'))},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_renew', 'Can renew due date'))},
        ),
    ]
