# Generated by Django 3.1.3 on 2020-11-28 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20201128_0446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_update', 'Can update'), ('can_delete', 'Can delete'), ('can_create', 'Can create'))},
        ),
    ]
